import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import RecoilWrapper from "@/components/RecoilWrapper/Wrapper";

const inter = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: {
    default:
      "Bestie - Your Trusted Online Marketplace for Buying and Selling Anything",
    template: "%s | Bestie",
  },
  description: "Besty is your friend. Buy anything here with trust.",
  metadataBase: new URL("https://bestie-frontend.vercel.app"),
  keywords: [
    "online marketplace",
    "buy and sell",
    "Bestie",
    "OLX",
    "Teezbazar",
    "trusted marketplace",
    "electronics",
    "fashion",
    "home goods",
    "second-hand items",
    "online shopping",
    "amazon",
    "prodcuts",
    "bestie",
    "online shop",
    "online store",
    "Bestie - Your Trusted Online Marketplace for Buying and Selling Anything",
    "Bestie online marketplace",
    "buy and sell products",
    "local classifieds website",
    "secondhand goods online",
    "affordable shopping deals",
    "quality used items",
    "cheap electronics deals",
    "sell your stuff online",
    "discount fashion shopping",
    "affordable home appliances",
    "mobile accessories sale",
    "best car listings online",
    "fashion trends shopping",
    "home decor deals",
    "tech gadgets online",
    "quick sell marketplace",
    "top electronics deals",
    "local online store",
    "best prices online",
    "affordable fashion accessories",
    "sell online easily",
    "cheap home essentials",
    "trending products 2024",
    "best bargains online",
    "quality tech gadgets",
    "home goods sale",
    "buy and sell online free",
    "affordable car listings",
    "best fashion marketplace",
    "top home appliances deals",
    "local buy and sell",
    "cheap electronics marketplace",
    "affordable home decor",
    "quality fashion deals",
    "buy electronics online",
    "home essentials shopping",
    "best deals online 2024",
    "cheap fashion accessories",
    "local buy and sell platform",
    "discount home appliances",
    "best local classifieds",
    "affordable online store",
    "fashion shopping deals",
    "sell products online",
    "best home goods deals",
    "quality mobile accessories",
    "cheap gadgets online",
    "best local deals",
    "affordable tech gadgets",
    "buy and sell locally",
    "affordable online marketplace",
    "best local deals 2024",
    "sell used items online",
    "top discount deals",
    "cheap fashion finds",
    "best electronics store",
    "quality secondhand products",
    "local marketplace deals",
    "buy electronics cheap",
    "home decor online store",
    "best mobile accessories",
    "affordable tech deals",
    "top fashion accessories",
    "quick sell platform",
    "discount home essentials",
    "best secondhand marketplace",
    "cheap home goods",
    "best local shopping",
    "quality fashion products",
    "affordable gadgets online",
    "sell electronics locally",
    "best deals marketplace",
    "cheap mobile accessories",
    "top home decor deals",
    "buy and sell free",
    "local online classifieds",
    "affordable electronics store",
    "best fashion deals 2024",
    "quality home appliances",
    "cheap tech gadgets",
    "top local marketplace",
    "affordable fashion trends",
    "best home essentials",
    "sell your products online",
    "cheap fashion products",
    "quality mobile gadgets",
    "top deals electronics",
    "affordable secondhand goods",
    "best home decor online",
    "cheap car listings",
    "local fashion deals",
    "top electronics store",
    "quality home goods",
    "best fashion shopping",
    "affordable home gadgets",
    "cheap fashion trends",
    "top mobile accessories",
    "sell your electronics",
    "best local store deals",
    "cheap gadgets store",
    "quality fashion finds",
    "affordable home listings",
    "top secondhand items",
    "best tech deals online",
    "cheap home appliances",
    "local buy and sell online",
    "top affordable products",
    "quality local deals",
    "best gadgets marketplace",
    "affordable fashion store",
    "cheap electronics online",
    "top home shopping deals",
    "sell fashion online",
    "best car deals online",
    "cheap home products",
    "local tech gadgets",
    "top home decor marketplace",
    "affordable local classifieds",
    "best fashion accessories store",
    "quality tech products",
    "cheap secondhand goods",
    "local affordable deals",
    "top home essentials store",
    "best electronics deals 2024",
    "affordable home store",
    "cheap gadgets marketplace",
    "quality home decor",
    "local fashion marketplace",
    "top mobile gadgets online",
    "best home goods marketplace",
    "cheap fashion accessories store",
    "affordable secondhand store",
    "best local electronics",
    "quality secondhand fashion",
    "cheap home decor items",
    "local tech deals",
    "top gadgets marketplace",
    "affordable fashion shopping",
    "best home goods store",
    "cheap home essentials store",
    "local secondhand marketplace",
    "top local classifieds 2024",
    "best tech products online",
    "affordable car listings",
    "cheap electronics deals online",
    "quality fashion store",
    "local home decor deals",
    "top affordable gadgets",
    "best local fashion deals",
  ],
  openGraph: {
    title: "Bestie",
    description:
      "Bestie - Your Trusted Online Marketplace for Buying and Selling Anything",
    url: "https://bestie-frontend.vercel.app",
    type: "website",
    images: [
      {
        url: "/logo.png",
        width: 800,
        height: 600,
        alt: "Bestie Logo",
      },
    ],
    locale: "en_US",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <RecoilWrapper>
        <body className={inter.className}>{children}</body>
      </RecoilWrapper>
    </html>
  );
}
